apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: project-c8720d77-cb3f-4556-9fe
      auth:
        workloadIdentity:
          clusterLocation: europe-west3-a
          clusterName: fh-burgenland-platform
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
