apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns
  - cert-manager.yaml
  - issuer.yaml
  - external-secrets.yaml
  - secret-stores.yaml
  - config-connector.yaml
