apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-stores
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/infrastructure/secret-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: external-secrets

  wait: true
  timeout: 5m
