apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    iam.gke.io/gcp-service-account: fh-burgenland-external-dns@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com
