apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: fh-burgenland-external-secrets@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com
