apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.5
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "fh-burgenland-external-secrets@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com"
