apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: fh-burgenland-config-connector@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com
