apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.16.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    crds:
      enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "fh-burgenland-cert-manager@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com"
