apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: fh-burgenland-cert-manager@project-c8720d77-cb3f-4556-9fe.iam.gserviceaccount.com
